# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/crypted";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."crypted".device = "/dev/disk/by-uuid/21c4c23a-efe3-4364-9b8f-5339b608f146";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0ADD-2745";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/cae578ba-d2db-43e4-94e8-b2b22a321a78"; }
    ];

  nix.maxJobs = lib.mkDefault 8;
}
